[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_pd_as = "2dZrwYmANJtCn9cKWTetA6SgNAV8nLwjGukLRcxHez6u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ic1993/.config/solana/id.json"

[scripts]
pda = "yarn run ts-node ./app/main.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
